  version: '3'

  services:
    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile.prod
      restart: always
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=production
        - NEXT_PUBLIC_STRAPI_API_URL=http://backend:1337
      depends_on:
        - backend

    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile.prod
      restart: always
      ports:
        - "1337:1337"
      environment:
        - NODE_ENV=production
        - DATABASE_CLIENT=postgres
        - DATABASE_HOST=database
        - DATABASE_PORT=5432
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      depends_on:
        - database

    database:
      image: postgres:14-alpine
      restart: always
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=${DATABASE_NAME}
        - POSTGRES_USER=${DATABASE_USERNAME}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  volumes:
    postgres-data: